### PR TITLE
build: support numpy2

### PR DESCRIPTION
**Pull request by eginhard**
Numpy 2 got released today, but can't be installed with gruut. This loosens the requirement.

I checked with the [ruff NPY201 rule](https://docs.astral.sh/ruff/rules/numpy2-deprecation/) that no uses of numpy in gruut need to be changed and `make test` also returns the same output for numpy 1.26.4 and 2.0.0 (in both cases the same 2 tests fail because $10/$100 didn't get normalised).

EDIT: also loosened the networkx requirement to allow version >=3

### CODE REVIEW

**Comment by eginhard** [comment]
I added another commit to also loosen the networkx requirement to support its new major version 3. The [migration guide](https://networkx.org/documentation/stable/release/migration_guide_from_2.x_to_3.0.html) doesn't seem to list anything that would be relevant for gruut. The output of `make test` also remains the same. 

@synesthesiam Would you consider releasing a new version of gruut with these changes? Gruut is the only dependency of Coqui that blocks using Numpy 2.

**Comment by synesthesiam** [comment]
Thanks! I will get a new release out here soon.

**Comment by synesthesiam** [comment]
Released as 2.4.0

**Comment by eginhard** [comment]
Thank you for the quick release!

**Pull request merged**
